const images = [
    {id:1, path:'/assets/shutterstock_469582127.jpg', meta: ["adorable", "african", "american", "baby", "beauty", "black", "blowing", "boy", "bubbles", "casual", "child", "childhood", "curls", "cute", "emotion", "ethnic", "expression", "fun", "funny", "grass", "green", "happiness", "happy", "infant", "innocence", "innocent", "kid", "laughing", "lifestyle", "little", "minority", "mixed", "nature", "outdoor", "outside", "park", "people", "person", "playing", "portrait", "race", "smile", "soap", "spring", "summer", "summertime", "sun", "sweet", "young"]},
    {id:2, path:'/assets/shutterstock_512123914.jpg', meta: ["40s", "addition", "adult", "balance", "box", "building", "concentrating", "construction", "contractor", "decorating", "diy", "female", "home", "improvement", "industry", "instrument", "interior", "kitchen", "level", "marking", "mature", "measurement", "measuring", "of", "one", "only", "pencil", "residential", "shelves", "spirit", "tool", "wall", "woman", "work", "worker"]},
    {id:3, path:'/assets/shutterstock_532011067.jpg', meta: ["360", "3d", "adult", "african", "african american", "amazing", "child", "christmas", "christmas eve", "christmas tree", "cute", "daughter", "day", "emotion", "excited", "expression", "family", "father", "fun", "games", "girl", "handsome", "happy", "headset", "holiday", "home", "kids", "little", "man", "modern", "new years eve", "occasion", "parenting", "pretty", "reality", "smile", "technology", "together", "virtual", "virtual reality", "vr", "xmas", "young"]},
    {id:4, path:'/assets/shutterstock_588775610.jpg', meta: ["affection", "architecture", "beautiful", "ben", "big", "boyfriend", "camera", "capital", "carefree", "city", "connected", "couple", "enjoyment", "famous", "fun", "girlfriend", "happiness", "happy", "historical", "landmark", "lifestyle", "london", "love", "man", "media", "memories", "partners", "people", "phone", "photo", "photograph", "photography", "posing", "relationship", "romantic", "selfie", "sharing", "sightseeing", "smart phone", "smiling", "social media", "taking", "technology", "together", "tourism", "tourist", "travel", "traveller", "vacation", "woman"]},
    {id:5, path:'/assets/shutterstock_1079331899.jpg', meta: ["activity", "beautiful", "beauty", "cardio", "care", "caucasian", "chubby", "clothing", "concept", "diet", "dieting", "exercise", "fat", "fatty", "female", "fitness", "health", "horizontal", "jogger", "jogging", "leisure", "lifestyle", "loss", "morning", "motion", "nature", "one", "outdoor", "outdoors", "oversized", "overweight", "park", "people", "person", "relaxation", "run", "runner", "sport", "sports", "strength", "stretching", "sunrise", "training", "up", "warming", "weight", "wellbeing", "woman", "workout", "young"]},
    {id:6, path:'/assets/shutterstock_1200999970.jpg', meta: ["automobile", "breeze", "business", "business man", "businessman", "car", "carefree", "city", "contemplation", "drive", "enjoy", "enjoyment", "evening", "face", "fun", "handsome", "happy", "imagination", "lifestyle", "light", "looking", "looking away", "male", "man", "mature", "matured", "mid adult man", "middle aged man", "night", "night city", "night life", "night lights", "nightlife", "on car", "people", "ride", "seat", "sitting", "smiling", "street", "taxi", "taxi new york", "think", "tourist", "transport", "transportation", "travel", "urban", "vacation", "window"]},
    {id:7, path:'/assets/shutterstock_1233205303.jpg', meta: ["asian", "business", "businesswoman", "casuals", "chinese", "copy", "desk", "entrepreneur", "female", "freelancer", "laptop", "lifestyle", "manager", "mature", "mixed race", "modern", "office", "one", "people", "person", "phone", "professional", "sitting", "space", "table", "technology", "woman", "working"]},
    {id:8, path:'/assets/shutterstock_1236301387.jpg', meta: ["active", "activity", "adults", "apparel", "autumn", "bicycle", "bike", "biker", "biking", "caucasian", "city", "close-up", "clothing", "countryside", "couple", "cycle", "cyclist", "e", "e-bike", "ebike", "electric", "electrobike", "females", "healthy", "helmet", "husband", "jacket", "lifestyle", "males", "man", "modern", "motor", "nature", "old", "outdoors", "outside", "park", "pensioners", "putting on", "recreation", "retired", "ride", "season", "senior", "sportswear", "technology", "urban", "wife", "woman"]},
    {id:9, path:'/assets/shutterstock_1387577558.jpg', meta: ["african", "box", "business", "businessman", "businesswoman", "delivery", "desk", "dropshipping", "ecommerce", "entrepreneur", "female", "looking", "males", "mature", "men", "merchandise", "multi ethnic", "office", "online store", "order", "owner", "package", "packaging", "packing", "parcel", "partner", "people", "person", "preparing", "product", "professional", "selling", "shipment", "shipping", "sitting", "small", "store", "two", "woman", "working", "young"]},
    {id:10, path:'/assets/shutterstock_1514919596.jpg', meta: ["body", "exercise", "fit", "fitness", "functional", "girl", "gym", "health", "healthy", "indoors", "lifestyle", "model", "muscles", "muscular", "people", "pilates", "plank", "planking", "slim", "space", "sport", "sportive", "sports person", "sportswear", "sportswoman", "sporty", "static", "strength", "strong", "style", "training", "weight", "woman", "workout", "yoga", "young"]}
];

export default images;